import os
import json
import logging
from pathlib import Path
from datetime import datetime

import google.generativeai as genai

from bot.core.git_utils import run_git, generate_branch_name
from bot.core.repo_reader import read_repo_context

log = logging.getLogger(__name__)

# ── Gemini Setup ────────────────────────────────────────
GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-1.5-pro-latest")

# ── Task Processing Logic ─────────────────────────────────────────

class TaskProcessor:
    def __init__(self, repo_path: str, gh_token: str, target_environment: str):
        self.repo_path = Path(repo_path)
        self.gh_token = gh_token
        self.target_environment = target_environment
        log.info(f"TaskProcessor initialized for repo: {self.repo_path}, env: {self.target_environment}")

    async def process_task(self, task_description: str, chat_id: int) -> str:
        """Process a task: generate code, commit, push, and open a PR."""
        log.info(f"Processing task for chat_id {chat_id}: {task_description}")

        # 1. Generate branch name
        branch_name = generate_branch_name(task_description)
        log.info(f"Generated branch name: {branch_name}")

        # 2. Sync and create branch
        try:
            run_git("checkout main", self.repo_path)
            run_git("pull origin main", self.repo_path)
            run_git(f"checkout -b {branch_name}", self.repo_path)
            log.info(f"Switched to new branch: {branch_name}")
        except RuntimeError as e:
            log.error(f"Failed to sync repo or create branch: {e}")
            return f"Failed to sync repo or create branch: {e}"

        # 3. Read repo context
        repo_context = read_repo_context(self.repo_path)
        log.info(f"Read repo context (length: {len(repo_context)} characters)")

        # 4. Generate changes with Gemini
        prompt = self._build_gemini_prompt(task_description, repo_context)
        log.info(f"Sending prompt to Gemini (length: {len(prompt)} characters)")
        try:
            response = model.generate_content(prompt)
            # Assuming the response format is a JSON string
            json_response = response.text.strip().lstrip('```json').rstrip('```')
            log.info(f"Gemini response received (length: {len(json_response)} characters)")
            changes = json.loads(json_response)
        except Exception as e:
            log.error(f"Gemini generation failed or invalid JSON: {e}\nResponse: {getattr(response, 'text', 'N/A')}")
            return f"Gemini generation failed or returned invalid JSON: {e}"

        # 5. Apply changes to the repo
        for file_change in changes.get("files", []):
            try:
                self._apply_file_change(file_change)
            except Exception as e:
                log.error(f"Failed to apply change for {file_change.get('path', 'N/A')}: {e}")
                run_git("reset --hard HEAD", self.repo_path) # Discard changes on error
                run_git("checkout main", self.repo_path)
                run_git(f"branch -D {branch_name}", self.repo_path)
                return f"Failed to apply changes, reverted branch: {e}"

        # 6. Commit changes
        commit_message = changes.get("commit_message", f"feat: Implement {task_description[:50]}...")
        try:
            run_git("add .", self.repo_path)
            run_git(f"commit -m \"{commit_message}\"", self.repo_path)
            log.info(f"Changes committed with message: {commit_message}")
        except RuntimeError as e:
            if "nothing to commit" in str(e):
                log.warning("No changes to commit, skipping commit and PR.")
                run_git("checkout main", self.repo_path)
                run_git(f"branch -D {branch_name}", self.repo_path)
                return "No changes were generated by Gemini, nothing to commit or PR."
            log.error(f"Failed to commit changes: {e}")
            run_git("reset --hard HEAD", self.repo_path) # Discard changes on error
            run_git("checkout main", self.repo_path)
            run_git(f"branch -D {branch_name}", self.repo_path)
            return f"Failed to commit changes, reverted branch: {e}"

        # 7. Push branch
        try:
            run_git(f"push -u origin {branch_name}", self.repo_path)
            log.info(f"Branch '{branch_name}' pushed to origin.")
        except RuntimeError as e:
            log.error(f"Failed to push branch: {e}")
            run_git("checkout main", self.repo_path)
            run_git(f"branch -D {branch_name}", self.repo_path)
            return f"Failed to push branch, reverted branch: {e}"

        # 8. Open PR
        pr_description = changes.get("pr_description", f"Automated PR for task: {task_description}")
        try:
            # gh cli requires being logged in via `gh auth login` and token in env
            pr_output = run_git(f'gh pr create --title "{commit_message}" --body "{pr_description}" --base main --head {branch_name} --repo {self.repo_path.name}', self.repo_path)
            pr_url = pr_output.strip().split('\n')[-1] # Usually the last line is the URL
            log.info(f"Pull request opened: {pr_url}")
            return f"Task completed! Pull request opened: {pr_url}"
        except RuntimeError as e:
            log.error(f"Failed to open PR: {e}")
            return f"Failed to open PR: {e}\nBranch pushed: {branch_name}"
        finally:
            # Always clean up by switching back to main
            run_git("checkout main", self.repo_path)
            log.info("Switched back to main branch.")

    def _build_gemini_prompt(self, task_description: str, repo_context: str) -> str:
        """Construct the prompt for Gemini Pro."""
        # This prompt encourages the desired JSON output format
        return f"""
You are an autonomous developer bot. Your task is to implement the requested feature or fix in the codebase.
Analyze the provided codebase context and produce *exact* file changes to accomplish the task.
Respond ONLY with a valid JSON object containing:
- "files": An array of file change objects. Each object must have:
    - "path": The path to the file (e.g., "src/main.py").
    - "action": "create", "modify", or "delete".
    - "content": The FULL content of the file for "create" or "modify" actions. For "delete", this can be an empty string.
- "commit_message": A concise commit message (e.g., "feat: Add new user endpoint").
- "pr_description": A detailed description for the pull request.

If a file needs to be modified, provide its *entire* new content, not just diffs.
If a file needs to be created, provide its *entire* content.
If a file needs to be deleted, set "content" to "" and "action" to "delete".

Always ensure the generated code is correct, follows best practices, and integrates seamlessly with the existing codebase.
If the task requires new dependencies, ensure they are added to `requirements.txt` or `pyproject.toml`.
If the task is about creating a new standalone script, assume it needs a `main` function or similar entry point.

---
Current Task: {task_description}

---
Codebase Context:
{repo_context}
"""

    def _apply_file_change(self, file_change: dict):
        """Apply a single file change (create, modify, or delete)."""
        file_path = self.repo_path / file_change["path"]
        action = file_change["action"]
        content = file_change.get("content", "")

        file_path.parent.mkdir(parents=True, exist_ok=True)

        if action == "create" or action == "modify":
            log.info(f"Action: {action} file: {file_path}")
            file_path.write_text(content)
        elif action == "delete":
            log.info(f"Action: {action} file: {file_path}")
            if file_path.exists():
                file_path.unlink()
            else:
                log.warning(f"Attempted to delete non-existent file: {file_path}")
        else:
            raise ValueError(f"Unknown action: {action} for file: {file_path}")
